### ISSUE TITLE
Missing serializers for Joda-Time LocalDate and LocalDateTime

### ISSUE THREAD

**Issue by RenniePet** [magro/kryo-serializers#29]
Am I correct in thinking that these are not implemented? 

I'm not an expert in Java or Joda-Time, but my understanding is that at least LocalDate can be useful, even in a distributed system that spans time zones. It can be used to specify a date, for example Christmas 2015 = 25 Dec. 2015, that is independent of time zone.

LocalDateTime is perhaps not so useful for serialization/deserialization screnarios, but maybe for cloning of objects that use it?

**Comment by magro** [comment]
You're right, currently there are no such serializers,  only for joda DateTime and Interval. It shouldn't be hard to write serializers for LocalDate and LocalDateTime, pull requests are welcome :-) If you need help writing them just ask.

**Comment by RenniePet** [comment]
OK, "I'll try anything once" - despite having limited Java skills and almost zero GitHub skills. 

Before me submitting a pull request, would you mind first taking a look at this: https://github.com/RenniePet/kryo-serializers/tree/additional-joda-time ?

It turned out to be more problematic than I expected. These two Joda-Time objects do have a millis fields burried inside them, but they are difficult to access (protected getters) and/or are not usable in the constructors.

I'm afraid there are no unit tests. I'm ashamed to admit that I've never written a unit test in my life. And even if I tried to fake it, I don't know how to run unit tests.

I've left your name and email address in the comments, partly because of the lack of unit tests. Would you prefer I inserted my own name?

Let me know what you think.

**Comment by magro** [comment]
Sorry for responding that late, I'm just coming back from vacation.

Am 03.03.2015 15:55 schrieb "RenniePet" <notifications@github.com>:
>
> OK, "I'll try anything once" - despite having limited Java skills and
almost zero GitHub skills.
>
> Before me submitting a pull request, would you mind first taking a look
at this:
https://github.com/RenniePet/kryo-serializers/tree/additional-joda-time ?
>
> It turned out to be more problematic than I expected. These two Joda-Time
objects do have a millis fields burried inside them, but they are difficult
to access (protected getters) and/or are not usable in the constructors.

Fine, I see the following potential improvements:
- use setInt(..., true) to save some bytes
- serialize localDateTime.getMillisOfDay instead of
hour/minute/second/millis to save bytes and calculate
hour/minute/second/millis on deserialization.

> I'm afraid there are no unit tests. I'm ashamed to admit that I've never
written a unit test in my life. And even if I tried to fake it, I don't
know how to run unit tests.

You could build upon one of the existing tests.
To run all tests do 'mvn test', to run a single test run 'mvn -
Dtest=SomeTestClass test' (see also
http://maven.apache.org/surefire/maven-surefire-plugin/examples/single-test.html).
If you're using an IDE you can also install a testng plugin (most IDEs only
support junit out of the box) and run the test from your IDE.

> I've left your name and email address in the comments, partly because of
the lack of unit tests. Would you prefer I inserted my own name?

Yes, you should receive the credits for your work. :-)

Cheers,
Martin

**Comment by RenniePet** [comment]
OK, I think I've made the improvements you requested. I'll try to create unit tests later today, and then submit a pull request.

**Comment by magro** [comment]
Cool!
Am 12.03.2015 07:37 schrieb "RenniePet" <notifications@github.com>:

**Comment by RenniePet** [comment]
A pull request has now been submitted. Hope you can use it.

One strange thing I've experienced is that the two "copy" unit test methods do not invoke my serialization/deserialization code at all! Kryo is apparently able to (and prefers to) copy these objects without serializing and deserializing them, at least as objects. Maybe it "serializes" and "deserializes" the individual fields? Anyway, these two copy unit test methods are somewhat misleading, since they aren't actually testing what they claim to be testing. Maybe they should be removed? (I'm running Java on an old Android device, if that has anything to do with it.)

**Comment by magro** [comment]
This is merged/released already.
